{% set name = "bimlpa" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bimlpa-{{ version }}.tar.gz
  sha256: b49b4b3010416d824b9b0f561e5a8afae41dd1692503113fd9c46eb8cf86dda5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scikit-learn
    - matplotlib-base
    - networkx

test:
  imports:
    - BiMLPA
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hbkt/BiMLPA
  summary: Community detection in bipartite networks using multi-label propagation algorithm
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
